spring:
  application:
    name: newsdigest

  # MySQL Driver configs
  datasource:
    url: jdbc:mysql://localhost:3306/newsdigest
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # JPA configs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: local